export interface RoleDefinition {
  readonly code: string;
  readonly label: string;
  readonly actions: readonly string[];
  readonly screens: readonly string[];
}

const BASE = {
  direccion: {
    code: 'AD',
    label: 'Alta dirección',
    actions: [
      'sesion.entrar',
      'notificacion.leer',
      'programa.consultar',
      'programa.aprobar',
      'programa.devolver',
      'dashboard.consultar',
      'revision_direccion.decidir',
      'registro.consultar',
      'informe.leer',
      'informe.acusar_recibo',
    ],
    screens: [
      'acceso.login',
      'inicio',
      'notificaciones',
      'programa.lista',
      'programa.aprobar',
      'dashboard.programa',
      'revision.direccion',
      'registro.buscar',
      'informe.ver',
    ],
  },
  gestor: {
    code: 'GE',
    label: 'Gestor',
    actions: [
      'sesion.entrar',
      'notificacion.leer',
      'programa.consultar',
      'programa.crear',
      'programa.editar',
      'plantilla.consultar',
      'plantilla.crear',
      'plantilla.editar',
      'plantilla.publicar',
      'auditor.consultar',
      'auditor.editar_ficha',
      'auditor.evaluar',
      'dashboard.analizar',
      'revision_direccion.presentar',
      'revision_programa.registrar_lecciones',
      'revision_programa.crear_version',
      'registro.consultar',
      'registro.exportar',
      'auditoria.consultar',
      'auditoria.crear',
      'auditoria.revisar_alcance',
      'auditoria.asignar_equipo',
      'accion.consultar_todas',
      'informe.aprobar',
    ],
    screens: [
      'acceso.login',
      'inicio',
      'notificaciones',
      'programa.lista',
      'programa.editar',
      'plantilla.lista',
      'plantilla.editar',
      'plantilla.publicar',
      'auditor.lista',
      'auditor.ficha',
      'auditor.evaluacion',
      'dashboard.programa',
      'revision.direccion',
      'revision.programa',
      'registro.buscar',
      'registro.historial',
      'auditoria.lista',
      'auditoria.alcance',
      'auditoria.equipo',
      'accion.lista',
      'informe.ver',
    ],
  },
  lider: {
    code: 'LI',
    label: 'Líder',
    actions: [
      'sesion.entrar',
      'notificacion.leer',
      'plantilla.consultar',
      'plantilla.proponer',
      'registro.consultar_propias',
      'auditoria.consultar',
      'auditoria.definir_alcance',
      'auditoria.confirmar_contacto',
      'auditoria.consultar_equipo',
      'auditoria.elaborar_plan',
      'ejecucion.presidir_apertura',
      'ejecucion.responder_checklist',
      'hallazgo.revisar',
      'ejecucion.presentar_cierre',
      'informe.revisar',
      'informe.firmar',
      'informe.distribuir',
    ],
    screens: [
      'acceso.login',
      'inicio',
      'notificaciones',
      'plantilla.lista',
      'plantilla.editar',
      'registro.buscar',
      'auditoria.lista',
      'auditoria.alcance',
      'auditoria.contacto',
      'auditoria.equipo',
      'auditoria.plan',
      'ejecucion.apertura',
      'ejecucion.checklist',
      'hallazgo.lista',
      'ejecucion.cierre',
      'informe.vista_previa',
      'informe.distribuir',
    ],
  },
  auditor: {
    code: 'AU',
    label: 'Auditor',
    actions: [
      'sesion.entrar',
      'notificacion.leer',
      'auditor.ver_ficha_propia',
      'auditoria.consultar_asignadas',
      'auditoria.consultar_plan',
      'ejecucion.asistir_apertura',
      'ejecucion.responder_checklist',
      'evidencia.capturar',
      'hallazgo.registrar',
      'ejecucion.asistir_cierre',
      'accion.consultar_por_verificar',
      'accion.verificar_eficacia',
    ],
    screens: [
      'acceso.login',
      'inicio',
      'notificaciones',
      'auditor.ficha',
      'auditoria.lista',
      'auditoria.plan',
      'ejecucion.apertura',
      'ejecucion.checklist',
      'ejecucion.evidencia',
      'hallazgo.lista',
      'ejecucion.cierre',
      'accion.lista',
      'accion.verificar',
    ],
  },
  dueno_proceso: {
    code: 'DU',
    label: 'Dueño de proceso',
    actions: [
      'sesion.entrar',
      'notificacion.leer',
      'registro.consultar_proceso',
      'auditoria.consultar_area',
      'auditoria.responder_contacto',
      'auditoria.aprobar_plan',
      'ejecucion.asistir_apertura',
      'ejecucion.aceptar_o_discrepar_cierre',
      'informe.leer',
      'accion.consultar_propias',
      'accion.crear',
      'accion.reportar_cierre',
    ],
    screens: [
      'acceso.login',
      'inicio',
      'notificaciones',
      'registro.buscar',
      'auditoria.lista',
      'auditoria.contacto',
      'auditoria.plan_aprobar',
      'ejecucion.apertura',
      'ejecucion.cierre',
      'informe.ver',
      'accion.lista',
      'accion.crear',
      'accion.cierre',
    ],
  },
  sistema: {
    code: 'SI',
    label: 'Sistema',
    actions: [
      'notificacion.enviar',
      'inicio.armar_menu',
      'programa.proponer_prioridad',
      'programa.registrar_aprobacion',
      'plantilla.validar_cobertura',
      'auditor.calcular_aptitud',
      'revision_direccion.exportar_resumen',
      'registro.versionar',
      'auditoria.bloquear_conflicto',
      'auditoria.notificar_plan',
      'hallazgo.exigir_evidencia',
      'evidencia.sellar',
      'informe.generar',
      'informe.exigir_rol_direccion',
      'accion.alertar_vencimiento',
      'accion.cerrar_no_conformidad',
    ],
    screens: [],
  },
  administrador: {
    code: 'AM',
    label: 'Administrador',
    actions: [
      'sesion.entrar',
      'notificacion.leer',
      'solicitud_clave.consultar',
      'solicitud_clave.aprobar',
      'solicitud_clave.rechazar',
      'perfil.editar',
      'perfil.cambiar_clave',
      'marca.editar',
    ],
    screens: ['acceso.login', 'inicio', 'notificaciones', 'solicitud.lista', 'perfil.editar', 'marca.editar'],
  },
} as const satisfies Record<string, RoleDefinition>;

const SUPERUSER_OWN = {
  actions: [
      'sesion.entrar',
      'notificacion.leer',
      'usuario.consultar',
      'usuario.crear',
      'usuario.editar',
      'usuario.cambiar_rol',
      'usuario.cambiar_estado',
      'usuario.invitar',
      'solicitud_clave.consultar',
      'solicitud_clave.aprobar',
      'solicitud_clave.rechazar',
      'perfil.editar',
      'perfil.cambiar_clave',
      'marca.editar',
      'menu.bloquear',
    ] as const,
  screens: [
      'acceso.login',
      'inicio',
      'notificaciones',
      'usuario.lista',
      'usuario.crear',
      'usuario.editar',
      'solicitud.lista',
      'perfil.editar',
      'marca.editar',
    ] as const,
};

const OPERATIVE_ROLES = [BASE.direccion, BASE.gestor, BASE.lider, BASE.auditor, BASE.dueno_proceso, BASE.administrador] as const;
type OperativeRole = (typeof OPERATIVE_ROLES)[number];
type SuperuserAction = (typeof SUPERUSER_OWN.actions)[number] | OperativeRole['actions'][number];
type SuperuserScreen = (typeof SUPERUSER_OWN.screens)[number] | OperativeRole['screens'][number];

export const ROLES = {
  ...BASE,
  superusuario: {
    code: 'SU',
    label: 'Superusuario',
    actions: [...new Set([...SUPERUSER_OWN.actions, ...OPERATIVE_ROLES.flatMap((role) => role.actions)])] as readonly SuperuserAction[],
    screens: [...new Set([...SUPERUSER_OWN.screens, ...OPERATIVE_ROLES.flatMap((role) => role.screens)])] as readonly SuperuserScreen[],
  },
} as const satisfies Record<string, RoleDefinition>;

export type RoleKey = keyof typeof ROLES;
export type SessionRole = Exclude<RoleKey, 'sistema'>;
export type AssignableRole = Exclude<SessionRole, 'superusuario'>;
export type Permission = (typeof ROLES)[RoleKey]['actions'][number];
export const SHARED_SCREENS = ['shell.navegacion', 'flujo.lista', 'flujo.guia', 'flujo.avance'] as const;
export type SharedScreenId = (typeof SHARED_SCREENS)[number];
export type ScreenId = (typeof ROLES)[RoleKey]['screens'][number] | SharedScreenId;
