import {
  ArrowRight,
  ArrowsClockwise,
  Bell,
  CalendarBlank,
  CalendarCheck,
  Camera,
  ChartLineUp,
  CheckCircle,
  ClipboardText,
  ClockCounterClockwise,
  FileText,
  Flag,
  Handshake,
  House,
  IdentificationCard,
  Key,
  ListBullets,
  ListChecks,
  MagnifyingGlass,
  NotePencil,
  PaintBrush,
  PaperPlaneTilt,
  PlayCircle,
  PlusCircle,
  PresentationChart,
  SealCheck,
  Target,
  UserCircle,
  UserGear,
  UserPlus,
  Users,
  UsersThree,
  WarningCircle,
  type Icon,
} from '@phosphor-icons/react';

export class IconCatalog {
  private static readonly ICONS: Readonly<Record<string, Icon>> = {
    'arrow-right': ArrowRight,
    'arrows-clockwise': ArrowsClockwise,
    bell: Bell,
    'calendar-blank': CalendarBlank,
    'calendar-check': CalendarCheck,
    camera: Camera,
    'chart-line-up': ChartLineUp,
    'check-circle': CheckCircle,
    'clipboard-text': ClipboardText,
    'clock-counter-clockwise': ClockCounterClockwise,
    'file-text': FileText,
    flag: Flag,
    handshake: Handshake,
    house: House,
    'identification-card': IdentificationCard,
    key: Key,
    'list-bullets': ListBullets,
    'list-checks': ListChecks,
    'magnifying-glass': MagnifyingGlass,
    'note-pencil': NotePencil,
    'paint-brush': PaintBrush,
    'paper-plane-tilt': PaperPlaneTilt,
    'play-circle': PlayCircle,
    'plus-circle': PlusCircle,
    'presentation-chart': PresentationChart,
    'seal-check': SealCheck,
    target: Target,
    'user-circle': UserCircle,
    'user-gear': UserGear,
    'user-plus': UserPlus,
    users: Users,
    'users-three': UsersThree,
    'warning-circle': WarningCircle,
  };

  public static resolve(key: string | undefined): Icon | undefined {
    return key === undefined ? undefined : IconCatalog.ICONS[key];
  }
}
